# Generated by Django 5.2.13 on 2026-04-24 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('EN', 'Entregado'), ('CA', 'Cancelado')], default='PE', max_length=2)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_est', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_destinatario', to='clientes.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envios.empleado')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_remitente', to='clientes.cliente')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rutas.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=2)),
                ('estado_nuevo', models.CharField(max_length=2)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.encomienda')),
            ],
        ),
    ]
