# Generated by Django 5.2.13 on 2026-04-24 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_create_missing_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellidos',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[A-Za-zÀ-ÖØ-öø-ÿ ]+$')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombres',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[A-Za-zÀ-ÖØ-öø-ÿ ]+$')]),
        ),
    ]
