# Generated by Django 5.2.13 on 2026-04-24 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[A-Za-zÀ-ÖØ-öø-ÿ ]+$')]),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[A-Za-zÀ-ÖØ-öø-ÿ ]+$')]),
        ),
    ]
