# Generated by Django 5.2.13 on 2026-04-24 02:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[A-Za-zÀ-ÖØ-öø-ÿ ]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[A-Za-zÀ-ÖØ-öø-ÿ ]+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nro_doc',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento solo debe contener dígitos.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener exactamente 9 dígitos numéricos.', regex='^\\d{9}$')]),
        ),
    ]
